from menu import mostrar_menu
from pedido import add_item, mostrar_pedido, finalizar, remover_item

def console():
    print("BIG RATÃO")
    print(f""" 
         ______     _____      _____       ______       ____     ________ 
        (_   _ \   (_   _)    / ___ \     (   __ \     (    )   (___  ___)
          ) (_) )    | |     / /   \_)     ) (__) )    / /\ \       ) )   
          \   _/     | |    ( (  ____     (    __/    ( (__) )     ( (    
          /  _ \     | |    ( ( (__  )     ) \ \  _    )    (       ) )   
         _) (_) )   _| |__   \ \__/ /     ( ( \ \_))  /  /\  \     ( (    
        (______/   /_____(    \____/       )_) \__/  /__(  )__\    /__\   

                               ..  . ......                                                        
.                             ...  .+:........                                                     
.                                ...xx;....                                                        
.                             .....:XX+;;:.....  ................ . ...                            
.                             .....:XXx++++++:....:::;;;::::..;;:......                            
.                             ......XXXxxxxxxxxxXXXXXXXXxx+++;;xx+;....                            
                                ....xXXXxXXXXXXx$X$$XXXXXxxxXXxXXXx;...                            
                                .. .;XXXXXXXXXXXx$$$$$XXxXXX$xX$$$Xx:..                            
                              ......:xX$$$$$XXXXxxX$$X$&x.;$X+XxxX$$;.... .                        
                              ......:+$$$$$$XX$XXXxxxXXXX$$XXXX$x.+$+.....                         
                       ............::x$$$$$$$$$XXXXX$$$$$$XXXXxx+;+XX+;:...                        
                       ............:;$$$$$$$$$$$$X$$$$$$$$$XXXxx++;;x+;;...                        
                      ......  .....;X$$$$$$$$$$$XX$$$$$$$$XXXxx+++;;;+;;:...                       
                               ...;+$$$$$$$$$$$$$XX$$$$$$$XXXXxxx+;::;++;......                    
                              ..::+X$$$$$$$$&&&$$$$$$$$$$XXXXxxx++;::;;+;.......  .    .....       
                              ...:+$$&$$$$$$&&&$$$$$$$$$$XXXXXxx++;;:;+;....................       
                              ...:X$$$$$$$$$&&$$$$$$$$$$$XXXXXxx++++++::.........  .........       
                              ..:+$$$$$$$$$$$&$&$$$$$$$$$XXXXXxx+x+xx+:....:................       
                              ..:$$$$$$$$$$$&$&$&$$$$$$$$XXXXXxxxxxxx;................... .        
                            ....x$$$$$$$$$$$$$&&$$$$$$$$$$X$Xx+;:;xxx:.....................   ..   
                          . ...x$$$$$&&$$$$$$$$$$$$$$$$XX$XXx+;::+xx;............. .............   
                           ...:X$$$$$$$$$$$$$$$$$$$$$$$$XXxxx+;::x++;:...... ..                    
                          ...:X$$$$$$$$$$$$$$$$$$$$$$$$XXx+xx+;;x++;;;:...... .                    
                      ..  ..:x$$$$$$$$$$$$$$$$$$$$$$$XXXxxxxxx+x+++;;;;......                      
                      .. ...;$$$$$$$$$$$$$$$$$$$$$$XXXXXXXxx+xx++++;;;;:...                        
                         ...x$$$$$$$$$$$$$$$$$$$XXXXXXXXxxxxx+x++++++;;;...                        
                      .. ..+$$$$$$$$$$$$$$$$XXXXxXxXXXxxxxxxx+++++++;;;;:... .                     
                        ...X$$$$$$$$$$$$$$$XXXXXXxxxxxxxxxxxxx++++;++;;++;...                      
                      ....x$$$$$$$$$$$$$$$XXXXXXXXXXxXxxXXxxxx+++xx+++;+++:....                    
                      ..:;X$$$$$$$$$$$$$$$X$$$XXXXXXXXXxxxXxxxxxxxxx++++xx;....        .....       
     .... ...............+$$$$$$$$$$$$$$$$$$$$$$XXXXXXXxXxxxxxxx+xxxx+++xxxx;...... ......::....   
      ..  ...;++:.......:X$$$$$$$$$&&$$$$$$$$$$XXXXXXXXxxxxxxxxxxx+++++++xXXXx;......:;+x++:....   
       .......++++:...:;XXXXXX$$$&&$$$$$$$$$X$XXX$XXXXXXxxxxxxxx++++++++xxX$$$$XXxxx++;;:.....     
     ...  ......:x+;+;;xxxxxXX$&&&&&$$$$$$$$X$$X$XXXxXXxxxxxx++++++++++++;:.:x$x+xxx++:.........   
      ..........:x+++++xxx$$$&&&&&&&&&$$$$$$XXXXXXXXxXXXxxxxx+++++++;+++++:::::Xx++;++;:........   
      ..:+;;;++++++++++x+;..;x&&&&&&&&$$$$$$XXXXXXXXXXXXxxxxxx+++;;+;;;++++.....xx+;+;;;;:......   
      ..;x++++++x++++++.....:x$$$&&&&&$$$$$$$$XXXXXXXxXXxxxxxxx+++;;;;;;+++;::...X+;++;:x+xXXx:.   
      .........+++++++......:;$$$$$&&&&$$$$$$$$XX$XXXXXXXxxxxx++++;;;;++++++;:...;+;:x;...;+x;..   
      .......+x++.;++......:;x$$$$$$$$$$$$$$$$$$XXXXXXXxXxxxxxx+++;+;;++;+++x+.:.:X+.;xx+.......   
  ..........x+x:..xxx......::+$$$&&&$$$$$$$$XXX$XXXXXXXxxxxxx++++++;;;;;;+++++x::.;x...xXx;... .  
....................... ...;;$$$$$$$$$$$$$$$$XXXX$XXXXxxXxxxx+x+x+++:;;;;+++++xx+:..............   
............... ...........:+$$&$$$$$$$$$$$$$$XXXXXXXXxxXxxxx+x+++++;+;;;++++x+xx+.........        
:::::....................:;x$$$&$$$$$$$$$$$$XXXXXXXXXXXxxxxxxxxx++++;;;;++;++++xxx+:.... .... .    
......::;;;;;;:........:::+$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXxxxxx++x+++++;++++++xxxxx+....  ..       
.. ............;++++;;:.:;$$$$&$$$$$$$$$$$$$$XXXXXXXXXXXXxxxx+x+xx++++;;++++x+xxxx+++..... .       
..    ..............:+xxX$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXxxxxx+xxx++++++++++xx+xxxxxx:....         
      ....   ........;+;+$&$$$$$$$$$$$$$X$$$$$$XXXXXXXXXXxxxxxxxxxx+;;+++++x+x+xxxxx++:....        
      ..  .   ......:;+xX$$$$$$$$$$$$$$$X$$$$$$$XXXXXXXXXxxxxxxxxxx+++++++xxxxxxxXxx++:.....       
              .. ...:++x$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXxxxxXxxxxx++++++xxXxxxxxxXxx+:.....       
                 ..:;;+$$&$$$$$$$$$$$$$$X$$$XX$$XXXXXXXXXXxxxxxxxxxxx+++xxxXxxXxXxXxx+:...         
    ..        .  ...:;+X$$$$$$$$$$$$$$$X$$$$XX$$XXXXXXXXXxXxxxxxxxxx+xxxxxxXXXxxXxxxx+:....        
    ..          ......+x$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXxXxxxxxxxxxxxxXXXXXXXXXXxx+:...         
                   ..:;;X$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXxxxxxxxxxxxxxxxXXXXXXXXXXXx++......       
                  ...:.;X$$$$$$$$$$$$$$$$$$$$$$$$X$XXXXXXXxxXxxxxxxxxxXXXXX$XXXXXxxxx;...         
                   ...:;+$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXxxxxxxxxXXxXXX$XXXXXxxx;...           
                  . ..:::x$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXxxxxxXXXXXxXX$XXXXXxx;....           
          ....    ......:.X$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXxxXxxXXX$$XXXXXX$XXXXXx.....           
          ....    .. ....:+$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXxXXXXX$$$$$$$$$XXX$XX+......           
          ....    ..  ....:x$$$$$$$$$$$$&$$$&&&$$$$$$$$$XXXXXXX$&&&&$$$$$$$$$$XX;.......           
    ..                . ...:X$$$$$$$&&&$XX+++:.:..:::::+;++;::...:x$&$$$&&$$$$X:........           
    ..                ......:$$$$$$$$:.............. ...........:::;++X$$$$$$XX$XXxx:...           
              . .....:;;+XXXX$$$$$X;:...........       .............::;+xxXXXXx;XXx;+:..           
             ... ..xxx++xX+;;+XXXx+;;:::..........     ..   ....  . .......;xXXxxxx+;...           
             .....;Xx+;+X+;;;;::...................                    ... ...................
""")
   

    print("1 - Ver cardápio")
    print("2 - Adicionar item ao pedido")
    print("3 - Ver pedido")
    print("4 - Finalizar pedido")
    print("5 - Remover item do pedido")
    print("0 - Sair\n")

def switch_case(desc):
    if desc == 1:
        mostrar_menu()
        print()
    elif desc == 2:
        add_item()
    elif desc == 3:
        mostrar_pedido()
    elif desc == 4:
        finalizar()
    elif desc == 5:
        remover_item()
    else:
        print("Opção inválida!\n")
